/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.gui;

import PlanetFood.Dao.EmployeesDao;
import PlanetFood.Pojo.Employees;
import PlanetFood.Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddEmpFrame extends javax.swing.JFrame {

   // HashMap<String,String>employees;
    public AddEmpFrame() {
        initComponents();
        super.setLocationRelativeTo(this);
        lblusername.setText("Hello"+UserProfile.getUsername());
        try
        {
           String str=EmployeesDao.getNewEmployeesId();
           txtEmpNo.setText(str);
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtaddnewemployee = new javax.swing.JLabel();
        txtempno = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        txtempname = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JTextField();
        txtsalary = new javax.swing.JLabel();
        txtSal = new javax.swing.JTextField();
        btnaddemp = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJob = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtaddnewemployee.setBackground(new java.awt.Color(0, 0, 0));
        txtaddnewemployee.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        txtaddnewemployee.setForeground(new java.awt.Color(255, 255, 255));
        txtaddnewemployee.setText("Adding New Employee Panel");
        jPanel3.add(txtaddnewemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 0, 590, 44));

        txtempno.setBackground(new java.awt.Color(0, 0, 0));
        txtempno.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtempno.setForeground(new java.awt.Color(255, 255, 255));
        txtempno.setText("EmpId");
        txtempno.setToolTipText("");
        jPanel3.add(txtempno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 210, 32));

        txtEmpNo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtEmpNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmpNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 250, 40));

        txtempname.setBackground(new java.awt.Color(0, 0, 0));
        txtempname.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtempname.setForeground(new java.awt.Color(255, 255, 255));
        txtempname.setText("EmpName");
        jPanel3.add(txtempname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, 31));

        txtEmpName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 250, 40));

        txtsalary.setBackground(new java.awt.Color(0, 0, 0));
        txtsalary.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtsalary.setForeground(new java.awt.Color(255, 255, 255));
        txtsalary.setText("Salary");
        jPanel3.add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 190, 30));

        txtSal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalActionPerformed(evt);
            }
        });
        jPanel3.add(txtSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 278, 250, 40));

        btnaddemp.setBackground(new java.awt.Color(0, 102, 102));
        btnaddemp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnaddemp.setForeground(new java.awt.Color(255, 255, 255));
        btnaddemp.setText("AddEmp");
        btnaddemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddempActionPerformed(evt);
            }
        });
        jPanel3.add(btnaddemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 210, -1));

        btnback.setBackground(new java.awt.Color(0, 102, 102));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel3.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 200, -1));

        lblLogout.setBackground(new java.awt.Color(0, 102, 102));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel3.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 100, -1));

        lblusername.setBackground(new java.awt.Color(0, 102, 102));
        lblusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Job");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 110, -1));

        txtJob.setBackground(new java.awt.Color(0, 102, 102));
        txtJob.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Admin", "Waiter", "Chief" }));
        txtJob.setToolTipText("");
        jPanel3.add(txtJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 250, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\asus\\Wallpaper\\administrator-male.png")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 270));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmpNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNoActionPerformed

    private void txtEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpNameActionPerformed

    private void txtSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalActionPerformed

    private void btnaddempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddempActionPerformed
        if (validateInput()==false)
        {
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
            return;
        }
        try
        {
            Employees e=new Employees();
            String empNo=(txtEmpNo.getText());
            String empName=txtEmpName.getText();
            String job=txtJob.getSelectedItem().toString();
            double EmpSal=Double.parseDouble(txtSal.getText());
            e.setEmpno(empNo);
            e.setEname(empName);
            e.setJob(job);
            e.setSal(EmpSal);
            if(EmployeesDao.addEmployee(e))
            JOptionPane.showMessageDialog(null, "Record Inserted SuccessFully");
            else
            JOptionPane.showMessageDialog(null, "Could not add the employee to the database");
        }
        catch(SQLException ex)
        {
            JOptionPane.showConfirmDialog(null, "Error in SQl"+ex,"Input Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showConfirmDialog(null, "Please input numeric for Employee No. and Salary"+ex);
            ex.printStackTrace();
        }
        clearAll();

    }//GEN-LAST:event_btnaddempActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        AddEmpFrame.this.dispose();
         AdminOptionsFrame aof=new AdminOptionsFrame();
         aof.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.yellow);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(Color.white);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int ans;
        ans=JOptionPane.showConfirmDialog(null,"Are u sure ?","Logout!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf= new LoginFrame();
            lf.setVisible(true);
        }
        
    }//GEN-LAST:event_lblLogoutMouseClicked
private boolean validateInput()
    {
        if(txtEmpNo.getText().isEmpty()|| txtEmpName.getText().isEmpty()|| txtSal.getText().isEmpty())
            return false;
        else 
            return true;
    }
public void clearAll()
{
 
  txtEmpName.setText("");
  txtSal.setText("");
  try{
 txtEmpNo.setText(EmployeesDao.getNewEmployeesId());
  }
  catch(Throwable th)
  {
      th.printStackTrace();
  }
  
}
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddemp;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JComboBox<String> txtJob;
    private javax.swing.JTextField txtSal;
    private javax.swing.JLabel txtaddnewemployee;
    private javax.swing.JLabel txtempname;
    private javax.swing.JLabel txtempno;
    private javax.swing.JLabel txtsalary;
    // End of variables declaration//GEN-END:variables
}
