/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.gui;

import PlanetFood.Pojo.UserProfile;
import PlanetFood.dbutil.DBConnection;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Devendra singh Yadav
 */
public class CashierOptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionsFrame
     */
    public CashierOptionsFrame() {
        initComponents();
        super.setLocationRelativeTo(this);
       lblusername.setText("Hello"+UserProfile.getUsername());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        AdminOption = new javax.swing.JPanel();
        AdminPlanetFood = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Empoptoin = new javax.swing.JPanel();
        jrTakeOrders = new javax.swing.JRadioButton();
        jrViewOrders = new javax.swing.JRadioButton();
        jrViewMenuList = new javax.swing.JRadioButton();
        jrViewTransaction = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblusername = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(102, 102, 102));

        AdminOption.setBackground(new java.awt.Color(0, 102, 102));
        AdminOption.setForeground(new java.awt.Color(0, 102, 102));
        AdminOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminPlanetFood.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AdminPlanetFood.setForeground(new java.awt.Color(255, 255, 255));
        AdminPlanetFood.setText("PLANET  FOOD CASHIER  PANEL");
        AdminOption.add(AdminPlanetFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Make A choice");
        AdminOption.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 281, -1));

        Empoptoin.setBackground(new java.awt.Color(0, 102, 102));
        Empoptoin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Empoptoin.setForeground(new java.awt.Color(102, 102, 102));

        jrTakeOrders.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(jrTakeOrders);
        jrTakeOrders.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jrTakeOrders.setForeground(new java.awt.Color(255, 255, 255));
        jrTakeOrders.setText("Take Orders");
        jrTakeOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrTakeOrdersActionPerformed(evt);
            }
        });

        jrViewOrders.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(jrViewOrders);
        jrViewOrders.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jrViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        jrViewOrders.setText("View Orders");
        jrViewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrViewOrdersActionPerformed(evt);
            }
        });

        jrViewMenuList.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(jrViewMenuList);
        jrViewMenuList.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jrViewMenuList.setForeground(new java.awt.Color(255, 255, 255));
        jrViewMenuList.setText("View Menu List");
        jrViewMenuList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrViewMenuListActionPerformed(evt);
            }
        });

        jrViewTransaction.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup5.add(jrViewTransaction);
        jrViewTransaction.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jrViewTransaction.setForeground(new java.awt.Color(255, 255, 255));
        jrViewTransaction.setText("View Transactions");
        jrViewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrViewTransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmpoptoinLayout = new javax.swing.GroupLayout(Empoptoin);
        Empoptoin.setLayout(EmpoptoinLayout);
        EmpoptoinLayout.setHorizontalGroup(
            EmpoptoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpoptoinLayout.createSequentialGroup()
                .addGroup(EmpoptoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrTakeOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrViewOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrViewMenuList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrViewTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 185, Short.MAX_VALUE))
        );
        EmpoptoinLayout.setVerticalGroup(
            EmpoptoinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpoptoinLayout.createSequentialGroup()
                .addComponent(jrTakeOrders)
                .addGap(25, 25, 25)
                .addComponent(jrViewOrders)
                .addGap(28, 28, 28)
                .addComponent(jrViewMenuList)
                .addGap(18, 18, 18)
                .addComponent(jrViewTransaction)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        AdminOption.add(Empoptoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 550, 350));

        btnDoTask.setBackground(new java.awt.Color(0, 102, 102));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 255, 255));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });
        AdminOption.add(btnDoTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 212, 40));

        btnQuit.setBackground(new java.awt.Color(0, 102, 102));
        btnQuit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(255, 255, 255));
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        AdminOption.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 213, 40));

        lblusername.setBackground(new java.awt.Color(0, 102, 102));
        lblusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        AdminOption.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 117, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\asus\\Pictures\\administrator-male.png")); // NOI18N
        AdminOption.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 168, 164));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cashier Options");
        AdminOption.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        lblLogout.setBackground(new java.awt.Color(0, 102, 102));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        AdminOption.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminOption, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminOption, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrViewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrViewOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrViewOrdersActionPerformed

    private void jrViewMenuListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrViewMenuListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrViewMenuListActionPerformed

    private void jrViewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrViewTransactionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrViewTransactionActionPerformed

    private void jrTakeOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrTakeOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrTakeOrdersActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        // TODO add your handling code here:
        if(jrTakeOrders.isSelected())
        {
            CashierOptionsFrame.this.dispose();
            TakeOrderFrame tof=new TakeOrderFrame();
            tof.setVisible(true);
          
            
        }
        else if(jrViewOrders.isSelected())
        {
            CashierOptionsFrame.this.dispose();
            ViewOrderFrame tof=new ViewOrderFrame();
            tof.setVisible(true);  
        }
        else if(jrViewMenuList.isSelected())
        {
            CashierOptionsFrame.this.dispose();
            ViewMenuListFrame vof=new ViewMenuListFrame();
            vof.setVisible(true);  
        }
        else if(jrViewTransaction.isSelected())
        {
            CashierOptionsFrame.this.dispose();
            ViewTransectionFrame tof=new ViewTransectionFrame();
            tof.setVisible(true);  
        }
        else
            JOptionPane.showMessageDialog(null,"Make A Choice ","Choose!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        int ans;
        ans=JOptionPane.showConfirmDialog(null, "Are u sure ?","Quitting!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            DBConnection.closeConnection();
            //JOptionPane.showMessageDialog(null,"Connection close Successfully","Success!",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int ans;
        ans=JOptionPane.showConfirmDialog(null,"Are u sure ?","Logout!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf= new LoginFrame();
            lf.setVisible(true);
        }
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.yellow);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(Color.white);
    }//GEN-LAST:event_lblLogoutMouseExited
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierOptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierOptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminOption;
    private javax.swing.JLabel AdminPlanetFood;
    private javax.swing.JPanel Empoptoin;
    private javax.swing.JButton btnDoTask;
    private javax.swing.JButton btnQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jrTakeOrders;
    private javax.swing.JRadioButton jrViewMenuList;
    private javax.swing.JRadioButton jrViewOrders;
    private javax.swing.JRadioButton jrViewTransaction;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblusername;
    // End of variables declaration//GEN-END:variables
}
