/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanetFood.gui;

import PlanetFood.Dao.CategoryDao;
import PlanetFood.Dao.OrderDetailDao;
import PlanetFood.Dao.OrdersDao;
import PlanetFood.Dao.ProductDao;
import PlanetFood.Pojo.OrderDetail;
import PlanetFood.Pojo.Orders;
import PlanetFood.Pojo.Product;
import PlanetFood.Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Devendra singh Yadav
 */
public class TakeOrderFrame extends javax.swing.JFrame {

    HashMap<String,Product>prodcuts;
    HashMap<String,String>categories;
    HashMap<String, Product> productList;
    private ArrayList<OrderDetail>orderList;
    private ArrayList<Product>prodLists;
    private Product p;
    private String CatId;
    private String prodName;
    private String catName;
    private String ordId;
    private double subtotal;
    private double actualtotal;
    private double grandtotal;
    private double discountAmount;
    private double gstamount;
    private double discountPer;
    private double amount;
    private DefaultTableModel model;
    private OrderDetail order;
    private OrderDetail OrderDetail;
    private String quantity=null;
    
    public TakeOrderFrame() {
        initComponents();
        jPanel1.setFocusable(true);
        super.setLocationRelativeTo(this);
        lblusername.setText("Hello"+UserProfile.getUsername());
       model=(DefaultTableModel)jtproductDetails.getModel();
      
                  
          
    }
    public void loadProductDetails()
    {
       try
       {
           categories=CategoryDao.getAllCategoryId();
           for(String catName:categories.keySet())
           jcProdCat.addItem(catName);
           
           ordId=OrdersDao.getNewId();
           txtOrderId.setText(ordId);
          
           do
           {
              String discountStr=null;
              discountStr=JOptionPane.showInputDialog("How much discount is offered ? ");
             try
             {
               discountPer=Double.parseDouble(discountStr);
               lblDiscount.setText("Discount("+discountPer+"%)");
             
               break;
             }
             
             
             catch(NumberFormatException th)
             {
                 JOptionPane.showMessageDialog(null,"Please Set numeric value for discount","Error!",JOptionPane.INFORMATION_MESSAGE);
                 th.printStackTrace();
             }
           }while(true);
           
      }
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null,"Exception in db","Exception!",JOptionPane.INFORMATION_MESSAGE);
           ex.printStackTrace();
       }
       
    
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddToBasket = new javax.swing.JPanel();
        lblprodCat = new javax.swing.JLabel();
        lblProdId = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        jcProdCat = new javax.swing.JComboBox<>();
        jcProdId = new javax.swing.JComboBox<>();
        txtProdName = new javax.swing.JTextField();
        lblProdPrice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtProdPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnaddToBasket = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCancelorder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblOrder = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        lblSubTotal = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        lblDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblGstAmount = new javax.swing.JLabel();
        txtGSTAmount = new javax.swing.JTextField();
        lblGrandTotal = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JTextField();
        btnPayNow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproductDetails = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAKE ORDER PANEL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 431, 40));

        btnAddToBasket.setBackground(new java.awt.Color(0, 153, 153));
        btnAddToBasket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Product To Take Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        btnAddToBasket.setForeground(new java.awt.Color(255, 255, 255));

        lblprodCat.setBackground(new java.awt.Color(51, 51, 51));
        lblprodCat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblprodCat.setForeground(new java.awt.Color(255, 255, 255));
        lblprodCat.setText("Product Category");

        lblProdId.setBackground(new java.awt.Color(51, 51, 51));
        lblProdId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProdId.setForeground(new java.awt.Color(255, 255, 255));
        lblProdId.setText("Product Id");

        lblProdName.setBackground(new java.awt.Color(51, 51, 51));
        lblProdName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProdName.setForeground(new java.awt.Color(255, 255, 255));
        lblProdName.setText("Product Name");

        jcProdCat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcProdCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProdCatActionPerformed(evt);
            }
        });

        jcProdId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcProdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProdIdActionPerformed(evt);
            }
        });

        txtProdName.setEditable(false);
        txtProdName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdNameActionPerformed(evt);
            }
        });

        lblProdPrice.setBackground(new java.awt.Color(51, 51, 51));
        lblProdPrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblProdPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblProdPrice.setText("Product Price");

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");

        txtProdPrice.setEditable(false);
        txtProdPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtProdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdPriceActionPerformed(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnaddToBasket.setBackground(new java.awt.Color(0, 153, 153));
        btnaddToBasket.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddToBasket.setForeground(new java.awt.Color(255, 255, 255));
        btnaddToBasket.setText("Add To Basket");
        btnaddToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddToBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnAddToBasketLayout = new javax.swing.GroupLayout(btnAddToBasket);
        btnAddToBasket.setLayout(btnAddToBasketLayout);
        btnAddToBasketLayout.setHorizontalGroup(
            btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddToBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProdPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcProdCat, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblprodCat)
                    .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnAddToBasketLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcProdId, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProdId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProdName, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lblProdName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(btnAddToBasketLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(btnAddToBasketLayout.createSequentialGroup()
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnaddToBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        btnAddToBasketLayout.setVerticalGroup(
            btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAddToBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprodCat)
                    .addComponent(lblProdId)
                    .addComponent(lblProdName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProdName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcProdCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcProdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdPrice)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnAddToBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddToBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(btnAddToBasket, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 630, 250));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Food Basket");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 164, 30));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 800, 190, 40));

        btnCancelorder.setBackground(new java.awt.Color(0, 153, 153));
        btnCancelorder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelorder.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelorder.setText("Cancel Order");
        btnCancelorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 800, 201, 40));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Basket Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        lblOrder.setBackground(new java.awt.Color(51, 51, 51));
        lblOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblOrder.setText("Order Id");

        txtOrderId.setEditable(false);
        txtOrderId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });

        lblSubTotal.setBackground(new java.awt.Color(51, 51, 51));
        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTotal.setText("Sub Total");

        txtSubTotal.setEditable(false);
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        lblDiscount.setBackground(new java.awt.Color(0, 153, 153));
        lblDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscount.setText("Discount");

        txtDiscount.setEditable(false);
        txtDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });

        lblGstAmount.setBackground(new java.awt.Color(51, 51, 51));
        lblGstAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGstAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblGstAmount.setText("GST Amount");

        txtGSTAmount.setEditable(false);
        txtGSTAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGSTAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGSTAmountActionPerformed(evt);
            }
        });

        lblGrandTotal.setBackground(new java.awt.Color(51, 51, 51));
        lblGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblGrandTotal.setText("Grand Total");

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGrandTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrandTotalActionPerformed(evt);
            }
        });

        btnPayNow.setBackground(new java.awt.Color(0, 153, 153));
        btnPayNow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPayNow.setForeground(new java.awt.Color(255, 255, 255));
        btnPayNow.setText("Pay Bill");
        btnPayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrder)
                    .addComponent(lblSubTotal)
                    .addComponent(lblGstAmount)
                    .addComponent(lblGrandTotal)
                    .addComponent(lblDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGSTAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrder)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGSTAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGstAmount))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrandTotal)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnPayNow)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 320, 370));

        jtproductDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtproductDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtproductDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTID", "PRODUCT NAME", "PRICE", "QUANTITY", "AMOUNT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtproductDetails);
        if (jtproductDetails.getColumnModel().getColumnCount() > 0) {
            jtproductDetails.getColumnModel().getColumn(0).setMinWidth(50);
            jtproductDetails.getColumnModel().getColumn(2).setMinWidth(50);
            jtproductDetails.getColumnModel().getColumn(3).setMinWidth(50);
            jtproductDetails.getColumnModel().getColumn(4).setMinWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 560, 350));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\asus\\Wallpaper\\mc3.gif")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 640));

        lblLogout.setBackground(new java.awt.Color(0, 102, 102));
        lblLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel1.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 100, -1));

        lblusername.setBackground(new java.awt.Color(0, 102, 102));
        lblusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdPriceActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnaddToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddToBasketActionPerformed
        // TODO add your handling code here:
        int result=validateInput();
        if(result==-1)
        {
          JOptionPane.showMessageDialog(null,"Please Input Quantity value type Neumeric","Input Error!",JOptionPane.PLAIN_MESSAGE);  
          return;
        }
        try
        { 
         String  price=txtProdPrice.getText();
         Object[]rows=new Object[5];
         Product p=productList.get(jcProdId.getSelectedItem().toString());
         rows[0]=jcProdId.getSelectedItem().toString();
         rows[1]=txtProdName.getText();
         rows[2]=price;
         rows[3]=quantity;
         amount=Double.parseDouble(price)*Double.parseDouble(quantity);
         rows[4]=amount;
         model.addRow(rows);
         
       
        amount=Double.parseDouble(price)*Double.parseDouble(quantity);
            
        actualtotal=actualtotal+amount;
        System.out.println(""+actualtotal);
        subtotal=actualtotal;
       //subtotal=(actualtotal+amount)-subtotal;
        System.out.println("subtotal before dis:"+subtotal);
         txtSubTotal.setText(String.valueOf(subtotal));
        System.out.println("subtotal after dis:"+subtotal);
        discountAmount=Math.round(discountPer*subtotal/100.0);
        txtDiscount.setText(String.valueOf(discountAmount));
        System.out.println("discount:"+discountAmount);
        subtotal=Math.round(subtotal-discountAmount);
        gstamount=Math.round(5*subtotal/100.0);
        txtGSTAmount.setText(String.valueOf(gstamount));
        grandtotal=subtotal+gstamount;
        txtGrandTotal.setText(String.valueOf(grandtotal));
           
      }
        catch(NumberFormatException th)
         {
                
                 th.printStackTrace();
         }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
        
        txtQuantity.setText("");
        
    }//GEN-LAST:event_btnaddToBasketActionPerformed

    private void jcProdCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProdCatActionPerformed
        // TODO add your handling code here:
         try
        {
          String catName=jcProdCat.getSelectedItem().toString();
          String catId=categories.get(catName).toString();
          productList=ProductDao.getProducatId(catId);
          jcProdId.removeAllItems();
           for(String prodId:productList.keySet())
           jcProdId.addItem(prodId);
           
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
        
    }//GEN-LAST:event_jcProdCatActionPerformed

    private void jcProdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProdIdActionPerformed
        // TODO add your handling code here:
         try
        {
          String catName=jcProdCat.getSelectedItem().toString();
          String catId=categories.get(catName).toString();
          if(jcProdId.getSelectedItem()==null)
          {
              return;
          }
          Product p=productList.get(jcProdId.getSelectedItem().toString());
           txtProdName.setText(p.getProdName());
           txtProdPrice.setText(p.getProdPrice()+"");
            //System.out.println(catId);
         // productList=ProductDao.getProducatId(catId);
          //jcProdId.removeAllItems();
          //for(String prodId:productList.keySet())
          //jcProdId.addItem(prodId);
           
          
        }
        catch(Throwable th)
        {
            th.printStackTrace();
        }
    }//GEN-LAST:event_jcProdIdActionPerformed

    private void txtProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CashierOptionsFrame c=new CashierOptionsFrame();
        c.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelorderActionPerformed
        // TODO add your handling code here:
            try
                
       {
           Orders e=new Orders();
           String oId=(txtOrderId.getText());
           e.setOrdId(ordId);
           OrderDetail ord=new OrderDetail();
          ord.setOrdId(oId);
           if(OrdersDao.CancelOrder(e, ord))
            JOptionPane.showMessageDialog(null, "Order Cancel SuccessFully...","Success",JOptionPane.INFORMATION_MESSAGE);
           else
               JOptionPane.showMessageDialog(null, " Order Cancel SuccessFully...");
       }
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null, "Error in SQl"+ex,"SQL Exception",JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
       }
       catch(Throwable ex)
       {
          
           ex.printStackTrace();
       }
         clearAll();
         for(int i=jtproductDetails.getRowCount()-1;i>=0;i--)
         {
          ((DefaultTableModel)jtproductDetails.getModel()).removeRow(i);  
         }
       
        
    }//GEN-LAST:event_btnCancelorderActionPerformed

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtGSTAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGSTAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGSTAmountActionPerformed

    private void txtGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrandTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrandTotalActionPerformed

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed
        // TODO add your handling code here:
        
           ArrayList<OrderDetail>orderlst=new ArrayList<>();
            OrderDetail od=new OrderDetail();
            od.setOrdId(ordId);
            od.setProdId(jcProdId.getSelectedItem().toString());
            od.setQuantity(Double.parseDouble(quantity));
            od.setCost(amount);
            orderlst.add(od);
           
            Orders os=new Orders();
            os.setOrdId(txtOrderId.getText().toString());
            
            long millis=System.currentTimeMillis();  
            java.sql.Date date=new java.sql.Date(millis);   
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MMM/yyyy");   
            System.out.println(formatter.format(date));  
            os.setOrddate(formatter.format(date));
            os.setGst(5);
            os.setGstamount(gstamount);
            os.setGrandtotal(grandtotal);
            os.setDiscount(discountAmount);
            os.setUserId(UserProfile.getUserId());
            os.setOrdamount(amount);
           
            String msg="Your Bill Details:\n Bill Amount: Rs"+actualtotal;
                   msg+="\nDiscount: Rs"+discountAmount;
                   msg+="\nGST: Rs"+gstamount;
                   msg+="\nAmount Payable: Rs"+grandtotal;
                   msg+="\nI Agree to Pay As Per";
                   
           JOptionPane.showMessageDialog(null,msg,"Reciepe Pay Mode !",JOptionPane.INFORMATION_MESSAGE);
                   
            try
            {
           boolean status = OrdersDao.addOrder(os,orderlst);
           if(status)
            
            {
                
                JOptionPane.showMessageDialog(null,"Order Placed Successfully... ","Success Orders!",JOptionPane.INFORMATION_MESSAGE);
                clearAll();
            }
           else
           {
               JOptionPane.showMessageDialog(null,"Order Not Placed ","Order Denied!",JOptionPane.ERROR_MESSAGE);
           }
            
            
        }
        
        catch(Throwable th)
        {
           th.printStackTrace();
        }
            for(int i=jtproductDetails.getRowCount()-1;i>=0;i--)
         {
          ((DefaultTableModel)jtproductDetails.getModel()).removeRow(i);  
         }
            
            
        
        
           
        
    }//GEN-LAST:event_btnPayNowActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
       
       loadProductDetails();    
    }//GEN-LAST:event_jPanel1FocusGained

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        // TODO add your handling code here:
     jPanel1.setFocusable(false);
     
        
    }//GEN-LAST:event_jPanel1FocusLost

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        int ans;
        ans=JOptionPane.showConfirmDialog(null,"Are u sure ?","Logout!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            this.dispose();
            LoginFrame lf= new LoginFrame();
            lf.setVisible(true);
        }

    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.yellow);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(Color.white);
    }//GEN-LAST:event_lblLogoutMouseExited
   public void showDataInTable()
    {
        try
            
        {
           ArrayList<Product>prodList=ProductDao.getAlldata();
           ArrayList<OrderDetail>ordList=OrderDetailDao.getAlldata();
           if(ordList.isEmpty()==true)
           {
               JOptionPane.showMessageDialog(null,"Sorry! No OrderDetails  Present","Error",JOptionPane.INFORMATION_MESSAGE);
           }
              else
           {
               Object[]rows=new Object[5];
               DefaultTableModel model=( DefaultTableModel)jtproductDetails.getModel();
               for(OrderDetail od:ordList)
               {
                   Product p=productList.get(jcProdId.getSelectedItem().toString());
                   rows[0]=od.getProdId();
                   rows[1]=p.getProdName();
                   rows[2]=p.getProdPrice();
                   rows[3]=od.getQuantity();
                   rows[4]=od.getCost();
                   model.addRow(rows);
               }
           }
        }
        catch(Throwable th)
        {
          th.printStackTrace();
        }
    }
   public int validateInput()
   {
       int result=1;
       quantity=txtQuantity.getText();
       if(quantity.isEmpty())
        result=-1;
       return result;
       
   }
   public void clearAll()
   {
      try
      {
       txtOrderId.setText(OrdersDao.getNewId());
      }
      catch(Throwable m)
      {
          m.printStackTrace();
      }
      txtSubTotal.setText("");
      txtDiscount.setText("");
      txtGSTAmount.setText("");
      txtGrandTotal.setText("");
            double subtotal;
      actualtotal=0;
      grandtotal=0;
     discountAmount=0;
     gstamount=0;
     amount=0;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeOrderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAddToBasket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelorder;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JButton btnaddToBasket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcProdCat;
    private javax.swing.JComboBox<String> jcProdId;
    private javax.swing.JTable jtproductDetails;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblGstAmount;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblProdId;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblProdPrice;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblprodCat;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtGSTAmount;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSubTotal;
    // End of variables declaration//GEN-END:variables
}
